apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: pia
  name: pia-jobbsender
  namespace: pia
spec:
  image: {{ image }}
  kafka:
    pool: {{ kafkaPool }}
  env:
    - name: JOBB
      value: {{ JOBB }}
    - name: JOBBLYTTER_TOPIC
      value: pia.jobblytter-v1
    - name: KAFKA_CLIENT_ID
      value: pia-jobbsender