apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: pia
  name: pia-jobbsender-nattlig
  namespace: pia
spec:
  image: {{ image }}
  schedule: "0 0 * * *"
  timeZone: "UTC"
  kafka:
    pool: {{ kafkaPool }}
  env:
    - name: JOBB
      value: {{ JOBB }}
    - name: JOBBLYTTER_TOPIC
      value: pia.jobblytter-v1