name: Deploy alerts to NAIS
on:
  push:
    branches:
      - main
    paths:
      - .nais/alerts-dev.yaml
      - .nais/alerts-prod.yaml
      - .github/workflows/deploy-alerts.yaml

permissions:
  id-token: write

jobs:
  apply-alerts:
    strategy:
      matrix:
        cluster: [ prod, dev ]
    name: Deploy alerts ${{ matrix.cluster }}-gcp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ matrix.cluster }}-gcp
          RESOURCE: .nais/alerts-${{ matrix.cluster }}.yaml
