name: Manuell kjøring av jobb
on:
  workflow_dispatch:
    inputs:
      cluster-name:
        description: 'Cluster som det skal deployes til'
        required: true
        default: 'dev-gcp'
        type: choice
        options:
          - 'prod-gcp'
          - 'dev-gcp'
      job-name:
        description: 'Jobb som skal kjøres'
        required: true
        default: 'næringsImport'
        type: choice
        options:
          - 'iaSakEksport'
          - 'iaSakStatistikkEksport'
          - 'iaSakLeveranseEksport'
          - 'iaSakSamarbeidsplanEksport'
          - 'iaSakSamarbeidEksport'
          - 'iaSakSamarbeidEksportEttSamarbeid'
          - 'iaSakSamarbeidBigQueryEksport'
          - 'spørreundersøkelseBigQueryEksport'
          - 'iaSakSamarbeidsplanBigqueryEksport'
          - 'næringsImport'
          - 'materializedViewOppdatering'
          - 'alleKategorierSykefraværsstatistikkDvhImport'
          - 'landSykefraværsstatistikkDvhImport'
          - 'sektorSykefraværsstatistikkDvhImport'
          - 'næringSykefraværsstatistikkDvhImport'
          - 'næringskodeSykefraværsstatistikkDvhImport'
          - 'bransjeSykefraværsstatistikkDvhImport'
          - 'virksomhetSykefraværsstatistikkDvhImport'
          - 'virksomhetMetadataSykefraværsstatistikkDvhImport'
          - 'publiseringsdatoDvhImport'
          - 'sjekkPubliseringsdatoOgImporter'
          - 'kalkulerResulterendeStatusForHendelser'
          - 'prosesserPlanlagtHendelse'
          - 'prosesserPlanlagteHendelser'
          - 'migrerEnVirksomhetTilNyFlyt'
          - 'migrerAlleVirksomheterTilNyFlyt'
          - 'engangsJobb'
      parameter-value:
        description: 'Valgfri parameter'
        required: false
        default: ''
        type: string

jobs:
  build:
    permissions:
      contents: write
      id-token: write
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/setup-java@v5.3.0
        with:
          distribution: temurin
          java-version: 25
      - uses: gradle/actions/setup-gradle@v6
        with:
          dependency-graph: generate-and-submit
      - name: Compile, run tests and build
        run: ./gradlew test installDist
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        with:
          platforms: linux/amd64,linux/arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build and push docker image
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: pia
          tag: ${{ github.ref == 'refs/heads/main' && 'latest' || 'branch_latest' }}
    outputs:
      image: ${{ steps.docker-push.outputs.image }}

  deploy:
    needs: build
    permissions:
      id-token: write
    name: Deployer jobb "${{ github.event.inputs.job-name  }}" til "${{ github.event.inputs.cluster-name  }}"
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v7.0.0
      - name: Deploy application to ${{ github.event.inputs.cluster-name  }}
        uses: nais/deploy/actions/deploy@v2
        env:
          IMAGE: ${{ needs.build.outputs.image }}
          CLUSTER: ${{ github.event.inputs.cluster-name  }}
          RESOURCE: .nais/nais.yaml
          VARS: .nais/${{ github.event.inputs.cluster-name  }}.yaml
          VAR: JOBB=${{ github.event.inputs.job-name  }},PARAMETER=${{ github.event.inputs.parameter-value }},RUN_ID=${{ github.run_id }}
